#!/usr/bin/env ruby

require 'optparse'

options = {}

opts = OptionParser.new do |o|
  o.on("--clean","Delete everything before re-cloning") do
    options[:clean] = true
  end
  o.on("--prune","Prune explicitly disabled plugins") do
    options[:prune] = true
  end
end
opts.parse!

git_bundles = [
	"git://github.com/juvenn/mustache.vim.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-markdown.git",
  "git@github.com:davetron5000/vim-pml.git",
  "git://github.com/edsono/vim-matchit.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/derekwyatt/vim-scala.git",
  "git://github.com/vim-scripts/Command-T.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/thisivan/vim-bufexplorer.git",
  "git://github.com/depuracao/vim-rdoc.git",
  "git://github.com/altercation/vim-colors-solarized.git",
  "git://github.com/tpope/vim-rails.git",
  "https://github.com/leshill/vim-json.git",
  "https://github.com/pangloss/vim-javascript.git",
  "https://github.com/tpope/vim-fugitive.git",
  "https://github.com/godlygeek/tabular.git",
  "git://github.com/dagwieers/asciidoc-vim.git",
  "git://github.com/epmatsw/ag.vim.git",
  "git://github.com/nanotech/jellybeans.vim.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  "git://github.com/mikewest/vimroom.git",
  "git://github.com/scrooloose/syntastic.git",
  "git://github.com/elixir-lang/vim-elixir.git",
  "https://github.com/mustache/vim-mustache-handlebars.git",
  "https://github.com/othree/html5.vim.git",
]

disabled = [
  "git://github.com/davetron5000/java-javadoc-vim.git",
  "git://github.com/davetron5000/javax-javadoc-vim.git",
  "git://github.com/kana/vim-xml-autons.git",
  "git://github.com/vim-scripts/VimClojure.git",
  "git://github.com/jacekd/vim-iawriter.git",
]


mine = [
  'vim-pml',
  'java-javadoc-vim',
  'javax-javadoc-vim',
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

if options[:clean]
  puts "Trashing everything (lookout!)"
  Dir["*"].each do |d| 
    if mine.include? d
      puts "Skipping #{d}; it's mine, manually pull to update"
    else
      FileUtils.rm_rf d
    end
  end
end

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  if File.exists?(dir)
    puts "  Skipping #{dir}, as it already exists"
  else
    puts "  Unpacking #{url} into #{dir}"
    `git clone #{url} #{dir}`
    if $?.success?
      FileUtils.rm_rf(File.join(dir, ".git"))
    else
      STDERR.puts "Problem with #{url}"
    end
  end
end

disabled.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  if File.exists?(dir)
    if options[:prune]
      puts "Cleaning #{dir} that is now disabled"
      FileUtils.rm_rf dir
    else
      puts "You've disabled #{dir}, put haven't used --prune.  Being safe and leaving it"
    end
  end
end
