#!/usr/bin/env ruby

git_bundles = [ 
	"git://github.com/juvenn/mustache.vim.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-markdown.git",
  "git@github.com:davetron5000/vim-pml.git",
  "git://github.com/edsono/vim-matchit.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/rosstimson/scala-vim-support.git",
  "git://github.com/vim-scripts/Command-T.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/mexpolk/vim-taglist.git",
  "git://github.com/kana/vim-xml-autons.git",
  "git://github.com/edsono/vim-bufexplorer.git",
  "git://github.com/depuracao/vim-rdoc.git",
  "git://github.com/altercation/vim-colors-solarized.git",
  "git://github.com/tpope/vim-rails.git",
  #"git://github.com/davetron5000/java-javadoc-vim.git",
  #"git://github.com/davetron5000/javax-javadoc-vim.git",
  "https://github.com/leshill/vim-json.git",
]

mine = [
  'vim-pml',
  'java-javadoc-vim',
  'javax-javadoc-vim',
]
vim_org_scripts = [
#  ["xml", "14039",  "ftplugin"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each do |d| 
  if mine.include? d
    puts "Skipping #{d}; it's mine, manually pull to update"
  else
    FileUtils.rm_rf d
  end
end

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

